### ISSUE TITLE
MAX_BACKUPS doesn't work

### ISSUE THREAD

**Issue by igorkamyshev** [umputun/github-backup-docker#1]
Hello! Thanks for this tool 🤓

I found one minor problem — MAX_BACKUPS doesn't affect amount of backups on disk.

My docker-compose:

```yml
version: "2"

services:
  github-backup:
    image: umputun/github-backup:latest
    container_name: "github-backup"
    hostname: "github-backup"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    environment:
      - GITHUB_USER=...
      - TOKEN=...
      - MAX_BACKUPS=2
      - TIME_ZONE=Europe/Moscow
    volumes:
      - ./data:/srv/var
```

But, now I have 11 directories with backups in `data`.

<img width="242" alt="Screenshot 2019-07-23 09 25 23" src="https://user-images.githubusercontent.com/26767722/61687744-cdd50700-ad2b-11e9-959b-0203f4dd8d32.png">

Can you fix it? 🤗
